# Reference datasets
ref: data/ref/T2T-CHM13.v2.fasta
ref_cdna: data/ref/Homo_sapiens.GRCh38.cdna.all.fa.gz
ref_cdna_paf: data/ref/T2T-CHM13.cdna.paf
ref_giab_vcf: data/ref/CHM13v2.0_HG2-T2TQ100-V1.1.vcf.gz
ref_hg002_q100: data/ref/hg002v1.1.fasta.gz

# DORADO settings
dorado : bin/dorado-0.8.1-linux-x64/bin/dorado
dorado_model:
  sup: "sup,5mCG_5hmCG"
  apk: "data/dorado_models/dna_r10.4.1_e8.2_apk_sup@v5.0.0"
  duplex: "sup"
models_directory: "data/dorado_models"
split_number: 100
process_subset_chunks: 3

herro_model : bin/herro-v1

gpu_queues: "gpu_srv010,gpu_srv019"

# Preprocessing settings
min_length : 
  default: 10000
  UL: 80000
min_mean_q : 9
genome_length : 3200000000

# Assembly settings
verkko_dryrun : False

# Hifiasm settings:
hifiasm : bin/hifiasm-0.25.0/hifiasm
hifiasm_opts:
  ont:   "--telo-m CCCTTA --dual-scaf --ul-cut 70000 -l1 --ont {ul}"
  herro: "--telo-m CCCTTA --dual-scaf --ul-cut 70000 -l1 {hq}"
  ont_trio: "--telo-m CCCTTA --dual-scaf --ul-cut 70000 -l0 --trio-dual --ont -1 {maternal} -2 {paternal} {ul}"
  herro_trio: "--telo-m CCCTTA --dual-scaf --ul-cut 70000 -l0 --trio-dual -1 {maternal} -2 {paternal} {hq}"
  rfhap: "--telo-m CCCTTA --dual-scaf --primary --ul-cut 70000 -l2 --n-hap 1 --ont {ul}"

yak : bin/yak/yak
mashmap : bin/MashMap/build/bin/mashmap

# Variant calling settings
X_PAR_file: bin/dipcall.kit/hs38.PAR.bed
run-dipcall: bin/dipcall.kit/run-dipcall
hapdiff: bin/hapdiff/hapdiff.py

# meryl kmer choice
K-mer: 37  # For QC
K-mer_phasing: 30 # For Trio phasing

kmer_refs:
  GE-MED-T2T00: "analysis_other/merqury_shortread/DX203429_02.meryl"

# T2T contigs
T2T_chromosomes: bin/T2T_Sequences/T2T_chromosomes.sh

# GQC
gqc:
  venv: bin/GQC/venv
  config: data/ref/gqc_config.yaml
  resourcedir: data/ref/gqc_resources
  fastk_binfolder: bin/FASTK/bin