import glob
import yaml
import re
from types import SimpleNamespace


configfile: os.path.join(workflow.basedir, "config.yml")


with open("data/datasets.yml") as f:
    datasets = yaml.safe_load(f)

with open("assembly/assemblies.yml") as f:
    asm = yaml.safe_load(f)


include: "rules/data_preparation.smk"
include: "rules/error_correction.smk"
include: "rules/assembly.smk"
include: "rules/qc_assembly.smk"


# Function to find all input FastQs and create required QC files
fq_files = [
    item
    for x in asm
    for item in get_assembly_input(SimpleNamespace(**{"asm": x})).values()
]
fq_qc = [
    x.replace("/input/", "/input_qc/").replace(".fastq.gz", "/read_stats.txt")
    for x in fq_files
]
# Create QC for all input BAM files
bam_qc = []
for dataset in datasets:
    for filetype in datasets[dataset]:
        if filetype != "POREC":
            bam_qc.append(f"data/bamstats/{dataset}/{dataset}.{filetype}/bamstats.txt")
            bam_qc.append(
                f"data/bamstats/{dataset}/{dataset}.{filetype}/cov.mosdepth.summary.txt"
            )


# Custom QC (Run stats)
fq_qc += [
    "assembly/input_qc/published/published.UL/read_stats.txt",
    "assembly/input_qc/published/published.UL.50x/read_stats.txt",
    "assembly/input_qc/published/published.UL.70x/read_stats.txt",
    "assembly/input_qc/published/published.UL.90x/read_stats.txt",
    "assembly/input_qc/published/published.HQ_herro/read_stats.txt",
    "assembly/input_qc/published/published.HQ_herro.120x/read_stats.txt",
    "assembly/input_qc/published/published.HQ_herro.60x/read_stats.txt",
    "assembly/input_qc/published/published.HQ_herro.35x/read_stats.txt"
    "assembly/input_qc/run_04399/run_04399.UL/read_stats.txt",
    "assembly/input_qc/run_04400/run_04400.UL/read_stats.txt",
]


rule all:
    input:
        fq_files,
        fq_qc,
        bam_qc,
        expand("assembly/output/{dataset}/assembly.fasta", dataset=asm.keys()),
        expand("assembly/qc/{dataset}/bandage_graph.png", dataset=asm.keys()),
        expand(
            "assembly/qc/{dataset}/qc_paftools_{module}.{hp}.txt",
            dataset=asm.keys(),
            module=["stat", "asmstat", "asmgene"],
            hp=["haplotype1", "haplotype2"],
        ),
        expand(
            "assembly/qc/{dataset}/dotplot.{hp}.pdf",
            dataset=asm.keys(),
            hp=["haplotype1", "haplotype2"],
        ),
