#!/usr/bin/env python3
"""
Run TADbit 3D chromatin structure modeling using IMP restraint-based approach.

TADbit uses the Integrative Modeling Platform (IMP) to generate 3D models
of chromatin structure from Hi-C/Pore-C contact matrices.

Usage:
    python 53_run_tadbit_modeling.py <matrix_file> <output_pdb> <output_models> \
        <resolution> <n_models> <n_keep> <max_dist> <lowfreq> <upfreq> <chr_name> [n_cpus]

Arguments:
    matrix_file  - Input contact matrix (space/tab separated)
    output_pdb   - Output PDB file for best model
    output_models - Output file with model statistics
    resolution   - Resolution in bp
    n_models     - Number of models to generate
    n_keep       - Number of best models to keep
    max_dist     - Maximum distance for restraints
    lowfreq      - Low frequency cutoff for restraints
    upfreq       - Upper frequency cutoff for restraints
    chr_name     - Chromosome name for labeling
    n_cpus       - Optional: number of CPUs (default: 8 or SLURM_CPUS_PER_TASK)
"""

import sys
import os
import argparse
import numpy as np


def run_tadbit_modeling(matrix_file, output_pdb, output_models, resolution,
                        n_models, n_keep, max_dist, lowfreq, upfreq, 
                        chr_name, n_cpus=8):
    """
    Run TADbit 3D modeling on a contact matrix.
    
    Parameters
    ----------
    matrix_file : str
        Path to input contact matrix file
    output_pdb : str
        Path to output PDB file
    output_models : str
        Path to output models summary file
    resolution : int
        Resolution in base pairs
    n_models : int
        Number of models to generate
    n_keep : int
        Number of best models to keep
    max_dist : float
        Maximum distance for restraints
    lowfreq : float
        Low frequency cutoff
    upfreq : float
        Upper frequency cutoff
    chr_name : str
        Chromosome name
    n_cpus : int
        Number of CPUs for parallel processing
    """
    try:
        from pytadbit import Chromosome
        from pytadbit.modelling.structuralmodels import StructuralModels
    except ImportError as e:
        raise ImportError(
            f"TADbit/pytadbit not installed. Please install via conda or singularity. Error: {e}"
        )
    
    # Read contact matrix
    print(f"Loading contact matrix from {matrix_file}")
    matrix = np.loadtxt(matrix_file)
    n_bins = matrix.shape[0]
    print(f"Matrix shape: {matrix.shape}, {n_bins} bins")
    
    if n_bins < 3:
        raise ValueError(f"Matrix too small ({n_bins} bins). Need at least 3 bins for modeling.")
    
    # Create chromosome object
    print(f"Creating TADbit Chromosome object for {chr_name}")
    chrom = Chromosome(name=chr_name)
    
    # Add experiment with Hi-C/Pore-C data
    # TADbit expects the data as a flattened upper triangle or full matrix
    chrom.add_experiment(
        'exp1',
        hic_data=[matrix.flatten().tolist()],
        resolution=resolution,
        norm_data=[matrix.flatten().tolist()]
    )
    
    exp = chrom.experiments['exp1']
    print(f"Experiment added with resolution {resolution}bp")
    
    # Optimize initial distance parameters
    print("Optimizing initial distance parameters...")
    try:
        exp.optimal_ini_dist(
            start=400, 
            end=1400, 
            n_models=min(20, n_models),
            n_keep=min(5, n_keep),
            lowfreq=-1, 
            upfreq=0
        )
    except Exception as e:
        print(f"Warning: optimal_ini_dist failed ({e}), using defaults")
    
    # Run 3D modeling
    print(f"Running 3D modeling with {n_models} models, keeping {n_keep}...")
    models = exp.model_region(
        start=1,
        end=n_bins,
        n_models=n_models,
        n_keep=n_keep,
        n_cpus=n_cpus,
        keep_all=False
    )
    
    print(f"Generated {len(models)} models")
    
    # Save best model as PDB
    pdb_base = output_pdb.replace('.pdb', '')
    models.write_pdb(pdb_base, models=[0])
    
    # TADbit adds .0.pdb suffix, rename to expected output
    tadbit_pdb = f"{pdb_base}.0.pdb"
    if os.path.exists(tadbit_pdb):
        os.rename(tadbit_pdb, output_pdb)
        print(f"Best model saved to {output_pdb}")
    elif os.path.exists(output_pdb):
        print(f"PDB already at expected location: {output_pdb}")
    else:
        # Try to find any generated PDB
        import glob
        pdb_files = glob.glob(f"{pdb_base}*.pdb")
        if pdb_files:
            os.rename(pdb_files[0], output_pdb)
            print(f"Renamed {pdb_files[0]} to {output_pdb}")
        else:
            raise FileNotFoundError(f"No PDB file generated by TADbit")
    
    # Save model summary
    with open(output_models, 'w') as f:
        f.write("# TADbit 3D models summary\n")
        f.write(f"# Chromosome: {chr_name}\n")
        f.write(f"# Resolution: {resolution}bp\n")
        f.write(f"# Total models generated: {n_models}\n")
        f.write(f"# Models kept: {n_keep}\n")
        f.write(f"# Number of bins: {n_bins}\n")
        f.write("#\n")
        f.write("# Model\tObjective_Function\tRadius_of_Gyration\n")
        
        for i, m in enumerate(models):
            objfun = m.get('objfun', 'NA')
            rog = m.get('radius_gyration', 'NA')
            f.write(f"Model_{i}\t{objfun}\t{rog}\n")
    
    print(f"Model summary saved to {output_models}")
    print("TADbit modeling completed successfully")
    
    return True


def create_placeholder_pdb(output_pdb, error_msg="Unknown error"):
    """Create a placeholder PDB file for failed runs."""
    with open(output_pdb, 'w') as f:
        f.write("HEADER    3D GENOME STRUCTURE - TADbit (FAILED)\n")
        f.write(f"REMARK    Error: {error_msg}\n")
        f.write("END\n")


def create_placeholder_models(output_models, error_msg="Unknown error"):
    """Create a placeholder models file for failed runs."""
    with open(output_models, 'w') as f:
        f.write(f"# TADbit failed: {error_msg}\n")


def main():
    parser = argparse.ArgumentParser(
        description='Run TADbit 3D chromatin structure modeling',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument('matrix_file', help='Input contact matrix file')
    parser.add_argument('output_pdb', help='Output PDB file')
    parser.add_argument('output_models', help='Output models summary file')
    parser.add_argument('resolution', type=int, help='Resolution in bp')
    parser.add_argument('n_models', type=int, help='Number of models to generate')
    parser.add_argument('n_keep', type=int, help='Number of models to keep')
    parser.add_argument('max_dist', type=float, help='Maximum distance for restraints')
    parser.add_argument('lowfreq', type=float, help='Low frequency cutoff')
    parser.add_argument('upfreq', type=float, help='Upper frequency cutoff')
    parser.add_argument('chr_name', help='Chromosome name')
    parser.add_argument('--n-cpus', type=int, default=None,
                       help='Number of CPUs (default: SLURM_CPUS_PER_TASK or 8)')
    
    args = parser.parse_args()
    
    # Determine number of CPUs
    if args.n_cpus:
        n_cpus = args.n_cpus
    else:
        n_cpus = int(os.environ.get('SLURM_CPUS_PER_TASK', 8))
    
    try:
        run_tadbit_modeling(
            matrix_file=args.matrix_file,
            output_pdb=args.output_pdb,
            output_models=args.output_models,
            resolution=args.resolution,
            n_models=args.n_models,
            n_keep=args.n_keep,
            max_dist=args.max_dist,
            lowfreq=args.lowfreq,
            upfreq=args.upfreq,
            chr_name=args.chr_name,
            n_cpus=n_cpus
        )
    except Exception as e:
        print(f"Error in TADbit modeling: {e}", file=sys.stderr)
        create_placeholder_pdb(args.output_pdb, str(e))
        create_placeholder_models(args.output_models, str(e))
        # Exit with 0 to allow pipeline to continue
        sys.exit(0)


if __name__ == '__main__':
    main()
