configfile: "config.yml"

#include: "rules/hicExplorer.smk"
include: "rules/pairs_to_hic_expand.smk"
include: "rules/fanc.smk"
#include: "rules/parse_contacts.smk"
include: "rules/cooler.smk"
#include: "rules/heatmap_plotting.smk"




