# Report configuration
report_filename: "Sequencinq_QC_PoreC.report.html"
force: true

#module:
#  - mosdepth
#  - pairtools

# Filename cleaning patterns
extra_fn_clean_exts:
  - ".pairs"
  - ".mosdepth"

# Report content
title: "PoreC Sequencing QC"
subtitle: "Individual flowcell results, based on wf-pore-c pipeline"
intro_text: ""

remove-samples:
 - "fastq_pass"
