settings:
  axis_h_pad: 0.02
  dim:
  - 2.0
  - 3.8
  dpi: 300
  format:
  - png
  - pdf
  layout: constrained
  legend_pos: right
  legend_prop: 0.15
  transparent: true
tracks:
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T00_1
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T00_1_chr5_haplotype1-0000014:45159751-53216507_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T00_1
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T00_1_chr5_haplotype1-0000014:45159751-53216507_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T00_1_chr5_haplotype1-0000014:45159751-53216507_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T00
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T00_chr5_haplotype1-0000021:45123493-51981590_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T00
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T00_chr5_haplotype1-0000021:45123493-51981590_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T00_chr5_haplotype1-0000021:45123493-51981590_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T00_chr5_haplotype1-0000021:45123493-51981590_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T01
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T01_rc-chr5_haplotype1-0000001:45441838-51046867_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T01
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T01_rc-chr5_haplotype1-0000001:45441838-51046867_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T01_rc-chr5_haplotype1-0000001:45441838-51046867_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T01_rc-chr5_haplotype1-0000001:45441838-51046867_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T05
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T05_chr5_haplotype1-0000017:45308734-53129579_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T05
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T05_chr5_haplotype1-0000017:45308734-53129579_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T05_chr5_haplotype1-0000017:45308734-53129579_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T05_chr5_haplotype1-0000017:45308734-53129579_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T07
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T07_chr5_haplotype1-0000029:45232050-53194757_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T07
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T07_chr5_haplotype1-0000029:45232050-53194757_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T07_chr5_haplotype1-0000029:45232050-53194757_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T07_chr5_haplotype1-0000029:45232050-53194757_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T08
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T08_chr5_haplotype1-0000020:45292224-52860863_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T08
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T08_chr5_haplotype1-0000020:45292224-52860863_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T08_chr5_haplotype1-0000020:45292224-52860863_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T08_chr5_haplotype1-0000020:45292224-52860863_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T15
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T15_rc-chr5_haplotype1-0000004:45331724-51679922_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T15
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T15_rc-chr5_haplotype1-0000004:45331724-51679922_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T15_rc-chr5_haplotype1-0000004:45331724-51679922_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T15_rc-chr5_haplotype1-0000004:45331724-51679922_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T16
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T16_chr5_haplotype1-0000024:45266168-53269668_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T16
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T16_chr5_haplotype1-0000024:45266168-53269668_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T16_chr5_haplotype1-0000024:45266168-53269668_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T16_chr5_haplotype1-0000024:45266168-53269668_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T17
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T17_chr5_haplotype1-0000002:45329278-50787269_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T17
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T17_chr5_haplotype1-0000002:45329278-50787269_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T17_chr5_haplotype1-0000002:45329278-50787269_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T17_chr5_haplotype1-0000002:45329278-50787269_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T18
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T18_chr5_haplotype1-0000018:45418474-52065082_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T18
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T18_chr5_haplotype1-0000018:45418474-52065082_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T18_chr5_haplotype1-0000018:45418474-52065082_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T18_chr5_haplotype1-0000018:45418474-52065082_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T19
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T19_rc-chr5_haplotype1-0000009:45155254-53035122_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T19
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T19_rc-chr5_haplotype1-0000009:45155254-53035122_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T19_rc-chr5_haplotype1-0000009:45155254-53035122_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap1/T2T19_rc-chr5_haplotype1-0000009:45155254-53035122_cdr.bed
  position: overlap
  type: label
- position: relative
  proportion: 0.01
  type: spacer
- options:
    fontsize: 5
    hide_x: false
    title_fontsize: 5
  position: relative
  proportion: 0.05
  type: position
