settings:
  axis_h_pad: 0.02
  dim:
  - 2.0
  - 3.8
  dpi: 300
  format:
  - png
  - pdf
  layout: constrained
  legend_pos: right
  legend_prop: 0.15
  transparent: true
tracks:
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T00_1
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T00_1_chr5_haplotype2-0000064:45120532-52615132_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T00_1
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T00_1_chr5_haplotype2-0000064:45120532-52615132_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T00_1_chr5_haplotype2-0000064:45120532-52615132_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T00
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T00_rc-chr5_haplotype2-0000062:45269692-53322004_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T00
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T00_rc-chr5_haplotype2-0000062:45269692-53322004_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T00_rc-chr5_haplotype2-0000062:45269692-53322004_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T00_rc-chr5_haplotype2-0000062:45269692-53322004_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T01
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T01_rc-chr5_haplotype2-0000048:45341170-52242752_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T01
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T01_rc-chr5_haplotype2-0000048:45341170-52242752_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T01_rc-chr5_haplotype2-0000048:45341170-52242752_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T01_rc-chr5_haplotype2-0000048:45341170-52242752_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T05
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T05_chr5_haplotype2-0000057:45223459-53116522_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T05
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T05_chr5_haplotype2-0000057:45223459-53116522_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T05_chr5_haplotype2-0000057:45223459-53116522_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T05_chr5_haplotype2-0000057:45223459-53116522_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T06
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T06_rc-chr5_haplotype2-0000064:45324673-53115330_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T06
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T06_rc-chr5_haplotype2-0000064:45324673-53115330_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T06_rc-chr5_haplotype2-0000064:45324673-53115330_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T06_rc-chr5_haplotype2-0000064:45324673-53115330_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T11
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T11_chr5_haplotype2-0000173:45373897-53274529_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T11
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T11_chr5_haplotype2-0000173:45373897-53274529_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T11_chr5_haplotype2-0000173:45373897-53274529_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T11_chr5_haplotype2-0000173:45373897-53274529_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T12
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T12_chr5_haplotype2-0000045:45227079-53148513_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T12
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T12_chr5_haplotype2-0000045:45227079-53148513_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T12_chr5_haplotype2-0000045:45227079-53148513_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T12_chr5_haplotype2-0000045:45227079-53148513_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T13
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T13_chr5_haplotype2-0000071:45649240-52765790_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T13
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T13_chr5_haplotype2-0000071:45649240-52765790_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T13_chr5_haplotype2-0000071:45649240-52765790_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T13_chr5_haplotype2-0000071:45649240-52765790_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T16
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T16_chr5_haplotype2-0000100:45102924-51596439_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T16
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T16_chr5_haplotype2-0000100:45102924-51596439_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T16_chr5_haplotype2-0000100:45102924-51596439_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T16_chr5_haplotype2-0000100:45102924-51596439_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T17
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T17_chr5_haplotype2-0000062:45389140-52537101_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T17
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T17_chr5_haplotype2-0000062:45389140-52537101_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T17_chr5_haplotype2-0000062:45389140-52537101_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T17_chr5_haplotype2-0000062:45389140-52537101_cdr.bed
  position: overlap
  type: label
- options:
    bg_border: true
    fontsize: 5
    hide_x: true
    legend: true
    legend_fontsize: 5
    legend_title: T2T18
    legend_title_fontsize: 5
    legend_title_only: true
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T18_chr5_haplotype2-0000053:45230356-52066293_rm.bed
  position: relative
  proportion: 0.15
  type: label
- options:
    bg_border: true
    bg_color: '#E6E6E6'
    color_map_file: /mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/analysis_other/cenmap/config/stv_annot_colors.tsv
    fontsize: 5
    hide_x: true
    hor_filter: 1
    legend: true
    legend_fontsize: 5
    legend_title: T2T18
    legend_title_fontsize: 5
    legend_title_only: true
    live_only: false
    mer_filter: 1
    sort_order: descending
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T18_chr5_haplotype2-0000053:45230356-52066293_stv.bed
  position: overlap
  type: hor
- options:
    arr_opt_bp_merge_blks: 100000
    arr_opt_bp_merge_units: 100000
    arr_opt_min_arr_hor_units: 1
    arr_opt_min_arr_len: 1
    arr_opt_min_arr_prop: 0.1
    arr_opt_min_blk_hor_units: 1
    fontsize: 5
    fwd_color: '#252525'
    hide_x: true
    legend: false
    live_only: true
    mer_filter: 2
    rev_color: '#252525'
    scale: 5
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T18_chr5_haplotype2-0000053:45230356-52066293_stv.bed
  position: relative
  proportion: 0.015
  type: horort
- options:
    alpha: 1
    color: '#FF99F0'
    fontsize: 5
    hide_x: true
    legend: false
    title_fontsize: 5
  path: ../../doc/figures/hor_plots/temp_hap2/T2T18_chr5_haplotype2-0000053:45230356-52066293_cdr.bed
  position: overlap
  type: label
- position: relative
  proportion: 0.01
  type: spacer
- options:
    fontsize: 5
    hide_x: false
    title_fontsize: 5
  position: relative
  proportion: 0.05
  type: position
